### ISSUE TITLE
[timelapse.py:getWebcamConfig()] - WARNING: no camera configured, using the fallback config

### ISSUE THREAD

**Issue by rcourtman** [mkuf/prind#116] opened 2024-02-26 19:37 UTC
I have my webcam set up and I can see that in the UI just fine. All I had to do was go add camera, change it to MPEG Streamer and the URLs were already correctly set as:

/webcam/?action=stream
/webcam/?action=snapshot

But I'm struggling to get the time lapse to work. I've selected the same camera that I set up in the camera section but you can see from the logs it's not seeing the camera. 

2024-02-26 19:33:50,126 [timelapse.py:getWebcamConfig()] - WARNING: no camera configured, using the fallback config
2024-02-26 19:33:52,131 [shell_command.py:_check_proc_success()] - Command (wget http://localhost:8080/?action=snapshot -O /tmp/timelapse/frame000001.jpg) cancelled
2024-02-26 19:33:52,131 [timelapse.py:newframe()] - getting newframe failed: wget http://localhost:8080/?action=snapshot -O /tmp/timelapse/frame000001.jpg

**Comment by mkuf** [comment] 2024-02-26 19:43
Hey there, 

that sounds like a duplicate of https://github.com/mkuf/prind/issues/113. 
You'll have to set the snapshot url in moonraker.conf to `http://webcam:8080/snapshot`. 

-Markus

**Comment by rcourtman** [comment] 2024-02-26 21:17
Ah thank you! 

In the end I landed on this which appears to be working:

[webcam LifeCam]
enabled: True
service: mjpegstreamer
stream_url: /webcam/?action=stream
snapshot_url: http://webcam:8080/snapshot

**Closed** 2024-02-26 21:20 UTC
