### ISSUE TITLE
Add support for CANbus passthrough

### ISSUE THREAD

**Issue by wanderling** [mkuf/prind#101] opened 2023-12-01 06:35 UTC
I would like to humbly request support for CANbus passthrough, most likely using can-gw. Here is one [example](https://www.lagerdata.com/articles/forwarding-can-bus-traffic-to-a-docker-container-using-vxcan-on-raspberry-pi). I was able to make it work on an Alpine and Ubuntu base docker images. I just don't have enough docker knowledge to dig in your code.

This would be revolutionary from a compatability standpoint.

This is my last hope to use docker for this. My next move if this won't work is VMs.

I appreciate your help.

**Comment by mkuf** [comment] 2023-12-03 17:41
This is a duplicate of https://github.com/mkuf/prind/issues/52. 

The code base has changed a bit since the initial solution was posted, but adding this snippet to your override file will allow acces to can devices. Any further configuration has to be done in klipper itself. 

```yaml
services:
  klipper:
    network_mode: host
```

**Closed by mkuf** 2023-12-03 17:41 UTC
